title: 빠른배송 성남퀵서비스
url: "https://seongnam.8222quick.com"
baseurl: ""

# 미래 날짜의 포스트도 표시하도록 설정 (핵심!)
future: true
timezone: Asia/Seoul

# 주소 끝에 index.html이 붙지 않아도 접속되게 설정
permalink: /:path/

# 빌드 설정
markdown: kramdown
highlighter: rouge

# 플러그인 설정
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# 컬렉션 설정
collections:
  towns:
    output: true

# 피드 플러그인 세부 설정
feed:
  path: /feed.xml
# 피드 주소 갱신용 주석: 2026-02-23-Final
